
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_user_auth
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database_user_auth:27017/user_auth
    depends_on:
      - mongodb
    networks:
      - my-network1

  mongodb:
    image: mongo:latest
    container_name: database_user_auth
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend --quiet --setParameter logLevel=2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network1

volumes:
  mongo-data:

networks:
  my-network1:
    driver: bridge
